"""Tests for the sanitizer pipeline."""

import pytest
from oma.core.sanitize import (
    Sanitizer,
    sanitize,
    strip_attributions,
    replace_em_dashes,
    straighten_quotes,
    strip_filler,
    collapse_whitespace,
)


class TestStripAttributions:
    def test_claude_attribution(self):
        text = "Hello world\nCo-Authored-By: Claude Sonnet <noreply@anthropic.com>"
        result = strip_attributions(text)
        assert "Claude" not in result
        assert "Anthropic" not in result.lower()

    def test_generated_with_claude(self):
        text = "Some text. Generated with Claude Code."
        result = strip_attributions(text)
        assert "Generated with Claude" not in result

    def test_chatgpt_attribution(self):
        text = "Output generated by ChatGPT-4"
        result = strip_attributions(text)
        assert "ChatGPT" not in result

    def test_gemini_attribution(self):
        text = "Generated with Gemini Pro"
        result = strip_attributions(text)
        assert "Gemini" not in result

    def test_deepseek_attribution(self):
        text = "Generated with DeepSeek v3"
        result = strip_attributions(text)
        assert "DeepSeek" not in result

    def test_preserves_normal_text(self):
        text = "This is a normal sentence about programming."
        assert strip_attributions(text) == text

    def test_as_ai_model(self):
        text = "As an AI language model, I cannot..."
        result = strip_attributions(text)
        assert "AI language model" not in result


class TestReplaceEmDashes:
    def test_clause_break(self):
        text = "The system works well -- even under load"
        result = replace_em_dashes(text)
        assert "--" not in result
        assert ", " in result

    def test_unicode_em_dash(self):
        text = "first point — second point"
        result = replace_em_dashes(text)
        assert "—" not in result

    def test_bullet_style(self):
        text = "— First item\n— Second item"
        result = replace_em_dashes(text)
        assert result.startswith("- First")
        assert "\n- Second" in result

    def test_preserves_single_hyphens(self):
        text = "well-known fact"
        assert replace_em_dashes(text) == text


class TestStraightenQuotes:
    def test_curly_singles(self):
        text = "‘hello’"
        result = straighten_quotes(text)
        assert result == "'hello'"

    def test_curly_doubles(self):
        text = "“hello”"
        result = straighten_quotes(text)
        assert result == '"hello"'


class TestStripFiller:
    def test_happy_to(self):
        text = "I'd be happy to help you with that. Here is the code."
        result = strip_filler(text)
        assert "happy to" not in result
        assert "Here is the code." in result

    def test_certainly(self):
        text = "Certainly! The answer is 42."
        result = strip_filler(text)
        assert "Certainly" not in result
        assert "The answer is 42." in result

    def test_great_question(self):
        text = "Great question! Let me explain."
        result = strip_filler(text)
        assert "Great question" not in result


class TestCollapseWhitespace:
    def test_multiple_blank_lines(self):
        text = "line1\n\n\n\n\nline2"
        result = collapse_whitespace(text)
        assert result == "line1\n\nline2"

    def test_trailing_spaces(self):
        text = "hello   \nworld  "
        result = collapse_whitespace(text)
        assert "   " not in result


class TestSanitizerPipeline:
    def test_full_pipeline(self):
        text = (
            "Certainly! I'd be happy to help.\n"
            "Here is the result — it works well.\n"
            "Generated with Claude Code.\n"
            "“Quoted text”"
        )
        result = sanitize(text)
        assert "Certainly" not in result
        assert "happy to" not in result
        assert "—" not in result
        assert "Claude" not in result
        assert "“" not in result

    def test_idempotent(self):
        text = "Some text with — em dashes and ‘quotes’"
        once = sanitize(text)
        twice = sanitize(once)
        assert once == twice

    def test_custom_pass(self):
        s = Sanitizer(enable_all=False)
        s.add_pass(lambda t: t.replace("foo", "bar"))
        assert s("foo baz") == "bar baz"
