import { mkdir } from "node:fs/promises";
await mkdir("apps/dashboard/src/generated", { recursive: true });
const browser = await Bun.build({
  entrypoints: ["apps/dashboard/src/browser.ts"],
  target: "browser",
  minify: true,
});
if (!browser.success)
  throw new AggregateError(browser.logs, "Browser build failed");
const script = await browser.outputs[0].text();
await Bun.write(
  "apps/dashboard/src/generated/browser.ts",
  "// Generated by bun run build.\nexport const BROWSER_SCRIPT = " +
    JSON.stringify(script) +
    ";\n",
);
if (!process.argv.includes("--browser")) {
  const build = await Bun.build({
    entrypoints: [
      "apps/cli/src/index.ts",
      "packages/core/src/index.ts",
      "apps/dashboard/src/web.ts",
    ],
    target: "bun",
    outdir: "dist",
    sourcemap: "external",
    naming: "[dir]/[name].[ext]",
  });
  if (!build.success) throw new AggregateError(build.logs, "Build failed");
  if (process.argv.includes("--compile")) {
    const args = [
      "bun",
      "build",
      "apps/cli/src/index.ts",
      "--compile",
      "--outfile",
      "dist/oma",
    ];
    if (process.env.BUN_BUILD_TARGET)
      args.push("--target", process.env.BUN_BUILD_TARGET);
    const child = Bun.spawn(args, { stdout: "inherit", stderr: "inherit" });
    if (await child.exited) throw new Error("Binary build failed");
  }
  console.log("Built Bun CLI, core, dashboard and browser bundles.");
}
